### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by christianalfoni** [cerebral/overmind#282]
This is stuff that is coming to Overmind:

## Docs
- [x] Clarify usage of `useOvermind` in React related to rendering
- [ ] Use effects to create value stores
- [ ] Handling offline apps
- [ ] Create TodoMVC example
- [x] Document using a function as derived, to receive props
- [ ] Improve touch surfaces (especially menu) on mobile

## Devtools
- [x] Hit metaKey + R to refresh app
- [x] Make devtools client decoupled from Electron (exciting stuff ahead)
- [x] Use hover with edit icon instead of clicking key to edit state
- [ ] Ability to lock state so that when Overmind initializes it sets that state immediately
- [ ] Allow changing size of actions list and plane using a splitter (long action names)
- [ ] Remember expanded paths when refreshing

## Overmind
- [ ] Fix issue with `logProxies` option, does not behave as it should
- [ ] add `filterMutation` and `waitMutation` operators: https://github.com/cerebral/overmind/pull/246/
- [ ] add `reaction` where you can pass callback to point to state and second callback to do something related to changes to that state. Needs to support nested change as well, not quite sure about the implementation, but will figure it out :)
- [ ] Blocked mutation, describe also probable reason in error (use json function)
- [ ] Use an `isProcessing` flag on derived so that you are able to derive from itself, accessing the cached value while processing. Need some fix to avoid stack overflow, so this seems to be a good way to do it
- [ ] Use of optional type `?` in state causes some weird translated state... though should probably not be used at all

**Comment by christianalfoni** [comment]
Haha... I just can not follow up on this stuff, it is really difficult. I am making some changes to my approach in the next release, so will talk about it then 😄
